export enum TypographyType {
  ROBOTO_14_REGULAR = 'ROBOTO_14_REGULAR',
  ROBOTO_16_REGULAR = 'ROBOTO_16_REGULAR',
  ROBOTO_16_MEDIUM = 'ROBOTO_16_MEDIUM',
  ROBOTO_18_REGULAR = 'ROBOTO_18_REGULAR',
  ROBOTO_18_MEDIUM = 'ROBOTO_18_MEDIUM',
  ROBOTO_20_MEDIUM = 'ROBOTO_20_MEDIUM',
  ROBOTO_22_BOLD = 'ROBOTO_22_BOLD',
  ROBOTO_24_MEDIUM = 'ROBOTO_24_MEDIUM',
  ROBOTO_30_MEDIUM = 'ROBOTO_30_MEDIUM',
  FORM_ERROR = 'FORM_ERROR',
}

export enum TypographyColor {
  BLACK = 'BLACK',
  WHITE = 'WHITE',
  LIGHT_GREY__ABAFBA = 'LIGHT_GREY__ABAFBA',
  LIGHT_GREY__A4A3A6 = 'LIGHT_GREY__A4A3A6',
  LIGHT_GREY__858da1 = 'LIGHT_GREY__858da1',
  LIGHT_GREY__6A6A6A = 'LIGHT_GREY__6A6A6A',
  LIGHT_GREY__757982 = 'LIGHT_GREY__757982',
  BLUE = 'BLUE',
}

export { default } from './Typography.react';
